url: https://www.applicodo.com
baseurl: ""

# Site settings
title: Applicodo
email: contact@applicodo.com
description: "Applicodo - We turn ideas into apps. Applicodo is a mobile development agency based in Iasi, Romania, that takes pride in building fine crafted iOS and Android applications. We are specialised in deliverying great user experience and we offer consultancy in branding and user acquisition."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ciprian Redinciuc
  pic: 1
  position: iOS Developer
  social:
    - title: twitter
      url: https://twitter.com/cyupa89
    - title: github
      url: https://github.com/cyupa
    - title: stack-overflow
      url: https://stackoverflow.com/users/736292/cyupa?tab=profile
- name: Andrei Frîncu
  pic: 2
  position: UI/UX Designer
  social:
    - title: twitter
      url: https://twitter.com/@andreifrincu
    - title: behance
      url: https://www.behance.net/andreifrincu
    - title: dribbble
      url: https://dribbble.com/andreifrincu
- name: Alexandru Chiriac
  pic: 3
  position: Android Developer
  social:
    - title: facebook
      url: https://www.facebook.com/alexandru.chiriac.7
    - title: linkedin
      url: https://www.linkedin.com/in/alexandru-chiriac-98463147

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/applicodo
  - title: facebook
    url: https://www.facebook.com/applicodo
  - title: github
    url: https://github.com/applicodo

# Postal address (add as many lines as necessary)
address:
  - line: Romania, Iasi

# Build settings
markdown: kramdown
permalink: pretty
